### ISSUE TITLE
Import

### ISSUE THREAD

**Issue by ripienaar** [telecoder/waypoints-manager-support#1]
Hello @telecoder 

I am keen to use Waypoints Manager but have some existing data I wish to import.  I tried converting a GPX file to GeoJSON but when sending the file to the app via share sheet it crashes.

Whats the way to import files, or perhaps there's a bug I can help get to the bottom of?

**Comment by telecoder** [comment]
Hi @ripienaar,

Thats the way to do it. Cold you please show me the structure of your file?.

Something like this should work:

```
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          -86.3,
          32.3777,
          73
        ]
      },
      "properties": {
        "name": "Montgomery",
        "state": "Alabama",
        "marker": "🦅"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          -134.4197,
          58.3019,
          17
        ]
      },
      "properties": {
        "name": "Juneau",
        "state": "Alaska",
        "marker": "🐻"
      }
    }
  ]
}
```

**Comment by ripienaar** [comment]
Here is a file I tried - it has many more items but all like this

```json
{
    "type": "FeatureCollection",
    "name": "waypoints",
    "crs": {
        "type": "name",
        "properties": {
            "name": "urn:ogc:def:crs:OGC:1.3:CRS84"
        }
    },
    "features": [
        {
            "type": "Feature",
            "properties": {
                "time": "2022\/10\/17 07:38:01+00",
                "name": "Pantheon",
                "desc": "17 Oct 2022 at 09:38:01"
            },
            "geometry": {
                "type": "Point",
                "coordinates": [
                    12.476855765730237,
                    41.89865708400361
                ]
            }
        }
    ]
}
```

**Comment by ripienaar** [comment]
With just this one entry - thinking maybe there are some other problems in other entries - I get just a error saying `Failed to parse geojson document`

**Comment by ripienaar** [comment]
It appears to be the missing elevation in `coordinates`

**Comment by telecoder** [comment]
yeah that's it, I was able to reproduce the issue. I'll release a fix soon.

Thanks for reporting!

**Comment by ripienaar** [comment]
Thanks a lot, do you have a property you parse for the time the waypoint was recorded and what format is that propety?

**Comment by telecoder** [comment]
I didn't include a property for that as was trying to make it very simple (just an app for learning swiftui), but may as well add it in the future, is that property really important for some application?

**Comment by ripienaar** [comment]
Nah I use these tools to track my places I visit. Convenient to just grab a waypoint whenever I am at some new place - so having a date is useful that’s all

**Comment by telecoder** [comment]
I will add it soon. In the meantime I applied a quick fix for the importing issue.

**Comment by ripienaar** [comment]
Nice. Import is fixed thanks a lot
